export const metadata = {
  title: "Cyna | Test",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="bg-red-400">
      <h1>Cyna - Accueil</h1>
    </div>
  );
}
